[android-auto]
available_while_in_call=false
can_play_native_media_during_vr=false
car_model=Unknown
car_year=2000
dpi=200
driver_pos=1
enabled=true
frame_rate=2
head_unit_name=MR2Dev
hide_clock=false
network_address=192.168.30.1
resolution=2
transport_type=network
ts_height=600
ts_width=1024
wifi_direct=true
wlan_bssid=CC:CC:CC:CC:CC:CC
wlan_name=HUD
wlan_password=ThisIsALongPassword

[car2pc]
FF_OFF=
FF_ON=PhoneBluetooth::Answer
NEXT_DISC=GUI::ChangePageNext
PREV_DISC=GUI::ChangePagePrev
RW_OFF=
RW_ON=PhoneBluetooth::Hangup
SCAN_OFF=PhoneBluetooth::VoiceRecognition
SCAN_ON=PhoneBluetooth::VoiceRecognition
serial_port=/dev/car2pc
text=false

[gpsd]
fence1pt1="-38.0511329405764, 145.12023383610452"
fence1pt2="-38.05144376777667, 145.11942299930348"
fence1pt3="-38.052253655402275, 145.11994175506427"
fence1pt4="-38.051957052861965, 145.12067703494105"
host=127.0.0.1
port=0

[i2c-light-sensor]
day_threshold=600
i2c_port=/dev/i2c-6
night_threshold=300
refresh_interval=3
sensor_model=modules/i2c-light-sensor/sensors/veml7700.json

[j2534]
reverse_page_index=3

[phone-bluetooth]
adapter=
adapterName=HUD

[reverse-camera]
camera=custom
gs_pipeline="videotestsrc name=vid_src ! capsfilter caps=\"video/x-raw,format=YV12\""

[rpi]
brightness=100
